### ISSUE TITLE
TAF - Add Copy

### ISSUE THREAD

**Issue by buzzedword** [nyxl-venoms/homefront.5dv.nyc#44]
TBD

**Comment by curieuxqueen** [comment]
Toronto Alpha Flight was founded in January 2019 with the goal of unifying Toronto Defiant fans in the spirit of community building, charitable giving, and sharing a passion for the rich history of our city. The group hosts local watch parties and meetups in the GTA and has become a social hub for local Overwatch League fans. Proudly led by community members, Toronto Alpha Flight is also the first charter member of Toronto Defiant’s Official Fan Association, The Defiance.

[St Michael’s Logo]

St. Michael’s Hospital was founded by the Sisters of St. Joseph in 1892 to care for the sick and poor of Toronto's inner city. Affectionately known as the Urban Angel, St. Michael’s is renowned for providing exceptional patient care. 

Toronto Alpha Flight’s mission for Homefront 2019 is to build power charging stations for the waiting rooms in the St. Michael’s Trauma Unit. All too often members of our community are called into the Trauma unit and find themselves unable to contact friends and loved ones due to lack of power on their phones. With your help, we will be able to ensure that no one ever faces this type of challenge isolated or alone.
